apiVersion: webapp.cloud.com/v1
kind: EC2Instance
metadata:
  name: ec2instance-sample
spec:
  instanceName: test-server
  instanceType: t3.small
  amiID: ami-0123456789abcdef0
  sshKey: my-key
  subnet: subnet-0123456789abcdef0
  tags:
    environment: development
    owner: xinyi
  storage:
    size: 20
    type: gp3
  additionalStorage:
    - size: 50
      type: gp3