apiVersion: webapp.cloud.com/v1
kind: EC2Instance
metadata:
  name: ec2instance-sample
spec:
  region: ap-southeast-1
  instanceName: test-server
  instanceType: t3.small
  amiID: ami-0d247eb021c5394df
  sshKey: ec2-operator-key
  subnet: subnet-0dfc41150596eaba5
  tags:
    environment: development
    owner: xinyi
  storage:
    size: 20
    type: gp3
  additionalStorage:
    - size: 50
      type: gp3